language: ruby
rvm:
- 2.5.3
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  run: rake db:migrate
  app: team-guardians
  api_key:
    secure: F3DSY79ODZjhsYBUZLzOMwNRK+vHhK5CGPZ6r0DS4RnKgfZ7IzoSyMSFAiVZYdW/a4j/SnBNvUbxoS/VftJLLpqqW05rynHNNQDQ5YklOZU2D28s8JWDpI6mB/pJbV6TzXJX+rPdDr6f+gC8SHrOW1IOm57WxIzJNuEFKHVTrvSN004WiritbqX6z7FW2VvabXAf5OrOmJ1dP8ku2V/JePExqevVoULxH/lahahDA4in8pG17lb8VZD+y6kZ7koTwQ2p+O6yME3cElL0MJTQ2i5hD0n7ru0BIH7E5W1IY6SraM6Bg86rj/yIlgkFtB+PuciyKisOgcpRXNNM6TbfafjyHHpNT0nYenF3pxX7lqOTx6TATnRHQ8BK1QhYrjGQ3hHydZFEGe7EBGNyfGl5ESGvOKKhHv+Bqqsp8XZScrepQzaJ+JJmh3a/uiQplZxnC1PUCD7GRnKjlEleBPjNbbCyAPnD1fKOTIPNTuDYS1HSkPerh5/ri+0X7zoQA4VN4H7JD57LYYcwwXb1QNgegbIhIbvLv8IoEhehBk0JY1BBhZJoWZaA+on1JqAKPT+BxtGQ1bgiYu+in+pwWWRF3jPdx9Rui3bswZzA37+1gnyYdIGbAIX9DuTqtkzZKfGTyu9vd4U42OuXEplEWG5VaUrRgNs4OpDsagkSd7SaNzA=
  on:
    repo: netguru-code-college/krk-18-guardians
