language: ruby
rvm:
- 2.5.3
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  run: rake db:migrate
  app: team-guardians
  api_key:
    secure: F3DSY79ODZjhsYBUZLzOMwNRK+vHhK5CGPZ6r0DS4RnKgfZ7IzoSyMSFAiVZYdW/a4j/SnBNvUbxoS/VftJLLpqqW05rynHNNQDQ5YklOZU2D28s8JWDpI6mB/pJbV6TzXJX+rPdDr6f+gC8SHrOW1IOm57WxIzJNuEFKHVTrvSN004WiritbqX6z7FW2VvabXAf5OrOmJ1dP8ku2V/JePExqevVoULxH/lahahDA4in8pG17lb8VZD+y6kZ7koTwQ2p+O6yME3cElL0MJTQ2i5hD0n7ru0BIH7E5W1IY6SraM6Bg86rj/yIlgkFtB+PuciyKisOgcpRXNNM6TbfafjyHHpNT0nYenF3pxX7lqOTx6TATnRHQ8BK1QhYrjGQ3hHydZFEGe7EBGNyfGl5ESGvOKKhHv+Bqqsp8XZScrepQzaJ+JJmh3a/uiQplZxnC1PUCD7GRnKjlEleBPjNbbCyAPnD1fKOTIPNTuDYS1HSkPerh5/ri+0X7zoQA4VN4H7JD57LYYcwwXb1QNgegbIhIbvLv8IoEhehBk0JY1BBhZJoWZaA+on1JqAKPT+BxtGQ1bgiYu+in+pwWWRF3jPdx9Rui3bswZzA37+1gnyYdIGbAIX9DuTqtkzZKfGTyu9vd4U42OuXEplEWG5VaUrRgNs4OpDsagkSd7SaNzA=
  on:
    repo: netguru-code-college/krk-18-guardians
env:
  secure: EcUbXEN+QZaKukYs20cRgr/Gqyijn0CSdhvcPZFJni3khq4pf8uLS1fzErrP31pEXGnEX3kmgCPyAdUl6c8Tkv4OOAfI9AoVhw5YX38yjuqLMmW2w9BN/7LJ9JF3pDs3YZtleQ9CGpFXEOw3SVaekG6Ls+zj2IY0VZ5a7+BcfXeBx6owPfK7MZpnMIOaiT8a6dEjlUEp9ITxLGTluEFcS3HCw+lI0Ab+Izeia68XijWA4Nj2M3d9/jh7MvCLCkHovunQRsj1hXkqVznjEV/1zS1/7BbdUc1VCX8r5vUvVG/B/j4Uk7Qp0JXRw7PjeQX37aA1UOkl9y8BFpi09OV7TWxavA5CkLuaz4OLrYUb6oXNBC/nUsZiu/3wpvC34EQ/8elisi2mQ0UoRDd6OaOe3kBwXq5yHVucvmklM/bT2B44XEvIP4bBr1i/7GLeG2vlDRjQSsLDdr9yOIwLMrpa2RSmZxFuSoiaNOpqsX1hRKaK6C8Msvkyga9ACOK/Gd4OeHBeY8gUvM/UAqZoWvyh9AAXFuGKTKEphkYBw0sjEvQTloz8pZlzlpEePbe0ko1GUufrUisWGzSSdDB/LcPbZzPdXSy60pt/vO2ColSAMHhPdPwDkUUd3sI++2ahEWzVdWRp+yz3+l2OS9EJ4c9eqeN3ga7CAZgwNjyF3MEgBms=
